### ISSUE TITLE
User friendly parsing 

### ISSUE THREAD

**Issue by j-l-s** [control-toolbox/CTBase.jl#48]
If a user makes a mistake then defining an abstract problem, the error message is related to the functional expression of the problem and the user has no real indication of the exact line (of the abstract definition) which reached the error.

Question is: how to give a better feedback to the user.

Idea to dig: encapsulate each functional call (= each generated line) in a try/catch block with explicit error message

A potential side effect is to rewrite the @def1 macro to avoid the actual global esc()

**Comment by jbcaillau** [comment]
@j-l-s I have noted:
- pass the current line (+ line number) to the parser to send a more informative message to the user
- pass this line to the runtime / `ocp` (`ocp.line = ...` in generated code) so that functional primitives can throw a more informative message (if the code line is present)
- encapsulate the generated code using `try ... catch` to catch runtime exceptions and still throw a more informative message
- encapsulate the macro body in a `try ... catch` to prevent any exception at the macro, and generate a code with a throw instead, that can be catched by the user (whereas the exception from the macro body cannot)

**Comment by jbcaillau** [comment]
@j-l-s please check #53
